services:
  db:
    image: postgres:16
    container_name: attendance_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: attendance_redis
    restart: always
    ports:
      - "6379:6379"

  ai-service:
    build: ./ai-service
    container_name: attendance_ai_service
    restart: always
    ports:
      - "9000:9000"

  backend:
    build: ./backend
    container_name: attendance_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
      - ai-service

  frontend:
    build: ./frontend
    container_name: attendance_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
